# Multi-stage build for small image size
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o identity ./internal/identity/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/identity .
# Ensure the .env file is available for the db connection
COPY --from=builder /app/.env . 
EXPOSE 8080
CMD ["./identity"]